### Registrar usuário
POST https://adonisjuuh.onrender.com/registro HTTP/1.1
Content-Type: application/json

{
    "name": "Júlia",
    "email": "juuhpimenta11@gmail.com",
    "password": "1234"

}

### Autenticar usuário
POST https://adonisjuuh.onrender.com/login HTTP/1.1
Content-Type: application/json

{
   "email": "juuhpimenta11@gmail.com",
   "password": "1234" 
}